### ISSUE TITLE
Problem with external Dll

### ISSUE THREAD

**Issue by hugobernardoni** [karayakar/monacoeditor#1]
Hello good day.
I'm using a project and I saw some problems, but this only occurs in the local version>
When I import an external dll (Serilog.AspNetCore for example), on the site it does not return results. (Follows images)
![image](https://user-images.githubusercontent.com/65677685/90029861-bac40a80-dc91-11ea-96c3-80790fbbb32e.png)

In its published version, it returns.
![image](https://user-images.githubusercontent.com/65677685/90029940-d7f8d900-dc91-11ea-9345-a6a9172ea9f2.png)

Could you tell me what changes in the published version but the git version?

Thank you

**Comment by Diaskhan** [comment]
U must run in your computer.
And resolve serilog package!

**Comment by Diaskhan** [comment]
Something like refs.Add(MetadataReference.CreateFromImage(byte[] image));

**Comment by Diaskhan** [comment]
No guide no explanation how to use monaco with cs. It is sad!

**Comment by Diaskhan** [comment]
Ive downloaded repo, updated nugets.
Add Serilog package from nuget.
Set to run from kestrel!

And voila.

![2020-09-19_19-14-56](https://user-images.githubusercontent.com/15046677/93668186-cedb0300-faac-11ea-8a9a-f4a4b9f62fc9.png)

**Comment by Diaskhan** [comment]
I guesse differnce with published version, that published version included Serilog package.

When U ve pressed Build, it resolves packeges that all ready loaded with Your solution!
Its Roslyn Baby.

**Comment by hugobernardoni** [comment]
> I guesse differnce with published version, that published version included Serilog package.
> 
> When U ve pressed Build, it resolves packeges that all ready loaded with Your solution!
> Its Roslyn Baby.

Hello, i resolved incluing Serilog package and worked. Thank you!

**Comment by hugobernardoni** [comment]
> I guesse differnce with published version, that published version included Serilog package.
> 
> When U ve pressed Build, it resolves packeges that all ready loaded with Your solution!
> Its Roslyn Baby.

Hello, i resolved incluing Serilog package and worked. Thank you!
